# Install
# 1. pip install pre-commit
# 2. pre-commit install(the first time you download the repo, it will be cached for future use)
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [
            "--show-source",
            "--count",
            "--statistics",
            "--extend-ignore=E203,E402,C901,E501,E101,E266,E731,W291,F821,W191,E122,E125,E127,E128,W293",
            "--per-file-ignores=__init__.py:F401",
        ] # when necessary, ignore errors, https://flake8.pycqa.org/en/latest/user/error-codes.html
        exclude: ^venv/ # exclude dir, e.g. (^foo/|^bar/)

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: ['--profile', 'black']
        exclude: >-
            (?x)^(
            .*__init__\.py$
            )
